### ISSUE TITLE
有个小请求

### ISSUE THREAD

**Issue by NeilTohno** [Morpheus1123/ZeroS-vapoursynth-template#1]
内容和下载地址1.xlsx
这个文件能不能单独分享出来啊
1drive下载不了来着
谢谢大大

**Comment by zka41101959** [comment]
？？？
在哪儿看到的

什么文件？VS滤镜库？
我本地还有一些VS/AVS相关配置文件，不知你要的是哪些

在 2019-03-31 00:14:31，"NeilTohno" <notifications@github.com> 写道：


内容和下载地址1.xlsx
这个文件能不能单独分享出来啊
谢谢大大

**Comment by zka41101959** [comment]
？？？
在哪儿看到的
什么文件？VS滤镜库？

在 2019-03-31 00:14:31，"NeilTohno" <notifications@github.com> 写道：


内容和下载地址1.xlsx
这个文件能不能单独分享出来啊
谢谢大大

**Comment by NeilTohno** [comment]
VS Plugins.rar里面的
VS滤镜库啊，对啊
谢谢啊

**Comment by Morpheus1123** [comment]
今天刚看到。。。我上传excel文档了，请查看。
